/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import config.migrations;
import controllers.Primary;
import helper.Message;
import java.io.IOException;
import java.sql.SQLException;
/**
 *
 * @author Klaus
 */
public class v_access extends javax.swing.JFrame {
    migrations mig = new migrations();
    Primary control = new Primary();
    Message msg = new Message();
    /**
     * Creates new form v_access
     */
    public v_access() {
        initComponents();
        this.windowsfull();
        this.awal();
        this.tblfile();
    }
    
    private void windowsfull(){
        setLocationRelativeTo(null);
    }
    
    private void awal(){
        btn_bukadb.setRequestFocusEnabled(true);
    }
    
    private void bukadb(){
        jfile.setEnabled(true);
    }
    
    private void buatdb() throws SQLException, IOException{
        mig.CreateDB();
    }
    
    private void bukafile(){
        control.OpenFileMSaccess();
        v_menu menu = new v_menu(control.getFile());
        menu.setVisible(true);
        dispose();
    }
    
    private void exit(){
        System.exit(0);
    }
    
    private void tblfile(){
        control.Tampilfile(jfile);
    }
    
    private void clickfile(){
        String d = jfile.getSelectedValue();
        String lok = "saves/" + d;
        v_menu menu = new v_menu(lok);
        menu.setVisible(true);
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        btn_bukadb = new javax.swing.JButton();
        btn_dbbaru = new javax.swing.JButton();
        btn_darifile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jfile = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MailList");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Open-Folder-Delete-icon.png"))); // NOI18N
        btn_exit.setText("Keluar");
        btn_exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_exit.setIconTextGap(2);
        btn_exit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        jPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 150, 80));

        btn_bukadb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database-search-icon (1).png"))); // NOI18N
        btn_bukadb.setText("Buka Database");
        btn_bukadb.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_bukadb.setIconTextGap(2);
        btn_bukadb.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_bukadb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukadbActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bukadb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, 80));

        btn_dbbaru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/database-add-icon.png"))); // NOI18N
        btn_dbbaru.setText("Database Baru");
        btn_dbbaru.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_dbbaru.setIconTextGap(2);
        btn_dbbaru.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_dbbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dbbaruActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dbbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 150, 80));

        btn_darifile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/open-file-icon.png"))); // NOI18N
        btn_darifile.setText("Buka Dari File");
        btn_darifile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_darifile.setIconTextGap(2);
        btn_darifile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_darifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_darifileActionPerformed(evt);
            }
        });
        jPanel1.add(btn_darifile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 150, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 500));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Pilih Database");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 260, 40));

        jfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jfileMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jfile);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 270, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bukadbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukadbActionPerformed
        // TODO add your handling code here:
        this.bukadb();
    }//GEN-LAST:event_btn_bukadbActionPerformed

    private void btn_dbbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dbbaruActionPerformed
        // TODO add your handling code here:
        try {
            this.buatdb();
            this.tblfile();
        } catch (SQLException | IOException ex) {
            msg.dbbuat();
        }
    }//GEN-LAST:event_btn_dbbaruActionPerformed

    private void btn_darifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_darifileActionPerformed
        // TODO add your handling code here:
        this.bukafile();
    }//GEN-LAST:event_btn_darifileActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        this.exit();
    }//GEN-LAST:event_btn_exitActionPerformed

    private void jfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jfileMouseClicked
        // TODO add your handling code here:
        this.clickfile();
    }//GEN-LAST:event_jfileMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_access.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new v_access().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bukadb;
    private javax.swing.JButton btn_darifile;
    private javax.swing.JButton btn_dbbaru;
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jfile;
    // End of variables declaration//GEN-END:variables
}
