/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import models.M_suratmasuk;
import helper.Message;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Klaus
 */
public class v_disposisi extends javax.swing.JDialog{
    M_suratmasuk model = new M_suratmasuk();
    Message msg = new Message(); 
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form v_disposisi
     * @param dis1
     * @param dis2
     * @param dis3
     * @param dis4
     * @param dis5
     * @param dis6
     * @param dis7
     * @param dis8
     * @param dir
     */
    public v_disposisi(String dis1, String dis2, String dis3, Date dis4, String dis5, String dis6, Date dis7, String dis8, String dir){
        initComponents();
        model.setDirectori(dir);
        this.windowsfull();
        this.awal();
        tno_urut.setText(dis1);
        tjenis_surat.setText(dis2);
        taasal_surat.setText(dis3);
        ttanggal_surat.setText(sdf.format(dis4));
        tno_surat.setText(dis5);
        taperihal.setText(dis6);
        ttanggal_diterima.setText(sdf.format(dis7));
        tno_agenda.setText(dis8);
    }
    
    private void windowsfull(){
        setLocationRelativeTo(null);
    }
    
    private void awal(){
        this.tno_urut.setEnabled(false);
        this.tjenis_surat.setEnabled(false);
        this.taasal_surat.setEnabled(false);
        this.ttanggal_surat.setEnabled(false);
        this.tno_surat.setEnabled(false);
        this.taperihal.setEnabled(false);
        this.ttanggal_diterima.setEnabled(false);
        this.tno_agenda.setEnabled(false);
        this.cb_kepada.setEnabled(true);
        this.taisi_disposisi.setEnabled(true);
        this.cb_kepada.requestFocus();
    }
    
    private void disposisibtn(){
        if(this.cb_kepada.getSelectedItem().equals("")
            ||this.taisi_disposisi.getText().equals("")){
            msg.validasi();
        }else{
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taisi_disposisi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        taasal_surat = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_kepada = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taperihal = new javax.swing.JTextArea();
        btn_disposisi = new javax.swing.JButton();
        tno_surat = new javax.swing.JTextField();
        tno_urut = new javax.swing.JTextField();
        tjenis_surat = new javax.swing.JTextField();
        tno_agenda = new javax.swing.JTextField();
        ttanggal_surat = new javax.swing.JTextField();
        ttanggal_diterima = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Disposisi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Jenis Surat");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        jLabel2.setText("Nomor Surat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 120, 30));

        jLabel3.setText("Nomor Urut");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, 30));

        jLabel4.setText("Asal Surat");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 120, 30));

        jLabel5.setText("Isi Disposisi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 30));

        jLabel6.setText("Tanggal Surat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 120, 30));

        taisi_disposisi.setColumns(20);
        taisi_disposisi.setRows(5);
        jScrollPane1.setViewportView(taisi_disposisi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 570, 110));

        taasal_surat.setColumns(20);
        taasal_surat.setRows(5);
        jScrollPane2.setViewportView(taasal_surat);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 450, 110));

        jLabel7.setText("Perihal");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 120, 30));

        jLabel8.setText("Tanggal Diterima");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 120, 30));

        jLabel9.setText("Nomor Agenda");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 120, 30));

        cb_kepada.setEditable(true);
        getContentPane().add(cb_kepada, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 570, 30));

        jLabel10.setText("Diteruskan Kepada");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 120, 30));

        taperihal.setColumns(20);
        taperihal.setRows(5);
        jScrollPane3.setViewportView(taperihal);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 450, 110));

        btn_disposisi.setText("Tampilkan");
        btn_disposisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disposisiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_disposisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 660, 130, 40));
        getContentPane().add(tno_surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 450, 30));
        getContentPane().add(tno_urut, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 70, 30));
        getContentPane().add(tjenis_surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, 30));
        getContentPane().add(tno_agenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 130, 30));
        getContentPane().add(ttanggal_surat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, 30));
        getContentPane().add(ttanggal_diterima, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 200, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_disposisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disposisiActionPerformed
        // TODO add your handling code here:
        this.disposisibtn();
    }//GEN-LAST:event_btn_disposisiActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_disposisi;
    private javax.swing.JComboBox<String> cb_kepada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taasal_surat;
    private javax.swing.JTextArea taisi_disposisi;
    private javax.swing.JTextArea taperihal;
    private javax.swing.JTextField tjenis_surat;
    private javax.swing.JTextField tno_agenda;
    private javax.swing.JTextField tno_surat;
    private javax.swing.JTextField tno_urut;
    private javax.swing.JTextField ttanggal_diterima;
    private javax.swing.JTextField ttanggal_surat;
    // End of variables declaration//GEN-END:variables
}
