/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;
import config.database;
/**
 *
 * @author Klaus
 */
public class v_menu extends javax.swing.JFrame {
    database con = new database();
    String dirct;
    /**
     * Creates new form v_menu
     * @param dir
     */
    public v_menu(String dir) {
        initComponents();
        con.setDirectori(dir);
        dirct = dir;
        this.windowsfull();
    }
    
    private void windowsfull(){
        setLocationRelativeTo(null);
        setExtendedState(v_menu.MAXIMIZED_BOTH);
    }
    
    private void kembali(){
        v_access a = new v_access();
        a.setVisible(true);
        dispose();
    }
    
    private void menusuratmasuk(){
        v_suratmasuk a = new v_suratmasuk(dirct);
        a.setVisible(true);
        dispose();
    }
    
    private void menusuratkeluar(){
        v_suratkeluar a = new v_suratkeluar(dirct);
        a.setVisible(true);
        dispose();
    }
    
    private void keluar(){
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        dblain = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mn_sm = new javax.swing.JMenu();
        mn_sk = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mn_k = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MailList");
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(880, 770));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu1.setText("Menu");

        dblain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        dblain.setText("Buka Database Lain");
        dblain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dblainActionPerformed(evt);
            }
        });
        jMenu1.add(dblain);
        jMenu1.add(jSeparator2);

        mn_sm.setText("Surat Masuk");
        mn_sm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_smMouseClicked(evt);
            }
        });
        jMenu1.add(mn_sm);

        mn_sk.setText("Surat Keluar");
        mn_sk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mn_skMouseClicked(evt);
            }
        });
        jMenu1.add(mn_sk);
        jMenu1.add(jSeparator3);

        mn_k.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        mn_k.setText("Keluar");
        mn_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_kActionPerformed(evt);
            }
        });
        jMenu1.add(mn_k);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Tools");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Report");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Export Database>>");
        jMenu2.add(jMenuItem4);
        jMenu2.add(jSeparator1);

        jCheckBoxMenuItem2.setText("1 Surat Masuk");
        jCheckBoxMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem2);

        jCheckBoxMenuItem1.setText("2 Surat Keluar");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jCheckBoxMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Bantuan");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dblainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dblainActionPerformed
        // TODO add your handling code here:
        this.kembali();
    }//GEN-LAST:event_dblainActionPerformed

    private void mn_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_kActionPerformed
        // TODO add your handling code here:
        this.keluar();
    }//GEN-LAST:event_mn_kActionPerformed

    private void jCheckBoxMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.menusuratmasuk();
    }//GEN-LAST:event_jCheckBoxMenuItem2ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.menusuratkeluar();
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void mn_smMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_smMouseClicked
        // TODO add your handling code here:
        this.menusuratmasuk();
    }//GEN-LAST:event_mn_smMouseClicked

    private void mn_skMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mn_skMouseClicked
        // TODO add your handling code here:
        this.menusuratkeluar();
    }//GEN-LAST:event_mn_skMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dblain;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenuItem mn_k;
    private javax.swing.JMenu mn_sk;
    private javax.swing.JMenu mn_sm;
    // End of variables declaration//GEN-END:variables
}
